name: Publish Package
on:
  release:
    types: [created]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn

      - name: Check types
        run: yarn check-types

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
