name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  generate-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup github-actions[bot]
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Generate new version
        run: |
          echo "VERSION=$(npm version ${{ github.event.inputs.version }} -m "chore: v%s release")" >> $GITHUB_ENV

      - name: Push changes & Create pull request
        run: |
          git checkout -b chore/$VERSION-release
          git push -u origin chore/$VERSION-release
          gh pr create -B main -t "chore: $VERSION release" -b "Release new version: $VERSION" -l release -a olekbaran,imLinguin -r olekbaran,imLinguin
        env:
          GITHUB_TOKEN: ${{ secrets.GA_PAT }}
