name: Generate version tag
on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate new version
        run: |
          echo "TAG=$(npm version ${{ github.event.inputs.version }} -m "chore: v%s release")" >> $GITHUB_ENV

      - name: Push new tag to repository
        run: git push origin $TAG

      - name: Push package.json version & Create pull request
        run: |
          git checkout -b chore/$TAG-release
          git push -u origin chore/$TAG-release
          gh pr create -B main -t "chore: $TAG release" -b "Release new version: $TAG" -l release -a olekbaran,imLinguin -r olekbaran,imLinguin
          git commit --amend --no-edit
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
